# Generated by Django 5.0.6 on 2025-09-27 03:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HazardDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dataset_type', models.CharField(choices=[('flood', 'Flood Susceptibility'), ('landslide', 'Landslide Susceptibility'), ('liquefaction', 'Liquefaction Susceptibility'), ('sea_level_rise', 'Sea Level Rise'), ('zonal_values', 'Zonal Values')], max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloodSusceptibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flood_susc', models.CharField(choices=[('LS', 'Low Susceptibility'), ('MS', 'Moderate Susceptibility'), ('HS', 'High Susceptibility'), ('VHS', 'Very High Susceptibility')], max_length=3)),
                ('original_code', models.CharField(max_length=10)),
                ('shape_length', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('orig_fid', models.IntegerField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4253)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazard_maps.hazarddataset')),
            ],
        ),
        migrations.CreateModel(
            name='LandslideSusceptibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landslide_susc', models.CharField(choices=[('LS', 'Low Susceptibility'), ('MS', 'Moderate Susceptibility'), ('HS', 'High Susceptibility'), ('VHS', 'Very High Susceptibility'), ('DF', 'Unknown Classification')], max_length=3)),
                ('original_code', models.CharField(max_length=10)),
                ('shape_length', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('orig_fid', models.IntegerField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4253)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazard_maps.hazarddataset')),
            ],
        ),
        migrations.CreateModel(
            name='LiquefactionSusceptibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquefaction_susc', models.CharField(choices=[('LS', 'Low Susceptibility'), ('MS', 'Moderate Susceptibility'), ('HS', 'High Susceptibility')], max_length=3)),
                ('original_code', models.CharField(max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4253)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazard_maps.hazarddataset')),
            ],
        ),
    ]
