# Generated by Django 5.2.6 on 2025-10-04 15:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_maps', '0002_alter_floodsusceptibility_geometry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('emergency', 'Emergency & Disaster-Related'), ('everyday', 'Everyday Life & Livability'), ('government', 'Government & Administrative')], max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('osm_id', models.BigIntegerField(unique=True)),
                ('osm_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['facility_type'], name='hazard_maps_facilit_a2ca60_idx'), models.Index(fields=['category'], name='hazard_maps_categor_0ce409_idx'), models.Index(fields=['osm_id'], name='hazard_maps_osm_id_d27992_idx')],
            },
        ),
    ]
