# Generated by Django 5.2.6 on 2025-10-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_maps', '0003_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landslidesusceptibility',
            name='landslide_susc',
            field=models.CharField(choices=[('LS', 'Low Susceptibility'), ('MS', 'Moderate Susceptibility'), ('HS', 'High Susceptibility'), ('VHS', 'Very High Susceptibility'), ('DF', 'Debris Flow - Critical Risk')], max_length=3),
        ),
    ]
