# Generated by Django 5.2.6 on 2025-10-11 13:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_maps', '0004_alter_landslidesusceptibility_landslide_susc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brgy_id', models.BigIntegerField()),
                ('brgycode', models.CharField(max_length=20)),
                ('b_name', models.CharField(max_length=100)),
                ('lgu_name', models.CharField(max_length=100)),
                ('area_has', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('perimeter', models.FloatField(blank=True, null=True)),
                ('hectares', models.FloatField(blank=True, null=True)),
                ('area_nso', models.FloatField(blank=True, null=True)),
                ('district', models.IntegerField(blank=True, null=True)),
                ('pop_2020', models.IntegerField(blank=True, null=True)),
                ('nsodata', models.CharField(blank=True, max_length=100, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazard_maps.hazarddataset')),
            ],
            options={
                'indexes': [models.Index(fields=['brgy_id'], name='hazard_maps_brgy_id_5fe1fa_idx'), models.Index(fields=['b_name'], name='hazard_maps_b_name_d0447e_idx'), models.Index(fields=['lgu_name'], name='hazard_maps_lgu_nam_41924b_idx')],
            },
        ),
    ]
