# Generated by Django 5.2.6 on 2025-10-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_maps', '0006_alter_hazarddataset_dataset_type_barangayboundarynew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarangayBoundary',
        ),
    ]
