# Generated by Django 5.2.7 on 2025-10-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hazard_maps", "0009_alter_hazarddataset_dataset_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZonalValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barangay_name", models.CharField(max_length=100)),
                ("barangay_code", models.CharField(db_index=True, max_length=50)),
                ("municipality", models.CharField(max_length=100)),
                ("street", models.CharField(blank=True, max_length=200, null=True)),
                ("vicinity", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "land_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Residential", "Residential"),
                            ("Commercial", "Commercial"),
                            ("Industrial", "Industrial"),
                            ("Agricultural", "Agricultural"),
                            ("Special", "Special"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("price_per_sqm", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hazard_maps.hazarddataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zonal Value",
                "verbose_name_plural": "Zonal Values",
                "ordering": ["barangay_name", "street"],
                "indexes": [
                    models.Index(
                        fields=["barangay_code"], name="hazard_maps_baranga_8dc0a0_idx"
                    ),
                    models.Index(
                        fields=["barangay_name"], name="hazard_maps_baranga_5fc8fb_idx"
                    ),
                    models.Index(
                        fields=["municipality"], name="hazard_maps_municip_80e16b_idx"
                    ),
                ],
            },
        ),
    ]
